package com.viclab.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF1760A5)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFD3E3FF)
val light_onPrimaryContainer = Color(0xFF001C39)
val light_secondary = Color(0xFF545F70)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFD8E3F8)
val light_onSecondaryContainer = Color(0xFF111C2B)
val light_tertiary = Color(0xFF764B9C)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFF1DAFF)
val light_onTertiaryContainer = Color(0xFF2D004F)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFDFCFF)
val light_onBackground = Color(0xFF1A1C1E)
val light_surface = Color(0xFFFDFCFF)
val light_onSurface = Color(0xFF1A1C1E)
val light_surfaceVariant = Color(0xFFDFE2EB)
val light_onSurfaceVariant = Color(0xFF43474E)
val light_outline = Color(0xFF73777F)
val light_inverseOnSurface = Color(0xFFF1F0F4)
val light_inverseSurface = Color(0xFF2F3033)
val light_inversePrimary = Color(0xFFA3C9FF)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFF1760A5)
val light_outlineVariant = Color(0xFFC3C6CF)
val light_scrim = Color(0xFF000000)

val dark_primary = Color(0xFFA3C9FF)
val dark_onPrimary = Color(0xFF00315C)
val dark_primaryContainer = Color(0xFF004882)
val dark_onPrimaryContainer = Color(0xFFD3E3FF)
val dark_secondary = Color(0xFFBCC7DB)
val dark_onSecondary = Color(0xFF263141)
val dark_secondaryContainer = Color(0xFF3C4758)
val dark_onSecondaryContainer = Color(0xFFD8E3F8)
val dark_tertiary = Color(0xFFDFB7FF)
val dark_onTertiary = Color(0xFF451969)
val dark_tertiaryContainer = Color(0xFF5D3282)
val dark_onTertiaryContainer = Color(0xFFF1DAFF)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF1A1C1E)
val dark_onBackground = Color(0xFFE3E2E6)
val dark_surface = Color(0xFF1A1C1E)
val dark_onSurface = Color(0xFFE3E2E6)
val dark_surfaceVariant = Color(0xFF43474E)
val dark_onSurfaceVariant = Color(0xFFC3C6CF)
val dark_outline = Color(0xFF8D9199)
val dark_inverseOnSurface = Color(0xFF1A1C1E)
val dark_inverseSurface = Color(0xFFE3E2E6)
val dark_inversePrimary = Color(0xFF1760A5)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFFA3C9FF)
val dark_outlineVariant = Color(0xFF43474E)
val dark_scrim = Color(0xFF000000)


val seed = Color(0xFF1760A5)